Clone the repository as follows:

[source,bash]
----
$ git clone https://github.com/micronaut-projects/micronaut-starter.git
----

`cd` into the `micronaut-starter` directory and run the following command:

[source,bash]
----
$ ./gradlew micronaut-cli:assembleDist
----

This will create a zip distribution of the CLI (named with the current version) in the `starter-cli/build/distributions/` folder.

You'll need to unzip this somewhere convenient.
For example, to unzip it to a dot directory in your user home, you could do:

[source,bash]
----
$ mkdir ~/.micronaut
$ unzip starter-cli/build/distributions/micronaut-cli-VERSION.zip -d ~/.micronaut
----

In your shell profile (`~/.bash_profile` if you are using the Bash shell), export the `MICRONAUT_HOME` directory (wherever you unzipped it to) and add the CLI path to your `PATH`:

.bash_profile/.bashrc
[source,bash]
----
export MICRONAUT_HOME=~/path/to/unzipped/cli
export PATH="$PATH:$MICRONAUT_HOME/bin"
----

TIP: If you're using SDKMAN! and don't want to mess with your $MICRONAUT_HOME, you can also point SDKMAN! to your local installation for dev purposes by using `sdk install micronaut dev path/to/unzipped/cli`

Reload your terminal or `source` your shell profile with `source`:

[source,bash]
----
$ source ~/.bash_profile
----

You are now able to run the Micronaut CLI.

[source,bash]
----
$ mn
| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
mn>
----
