plugins {
    id("org.openrewrite.build.recipe-library-base") version "1.126.2"

    // Configures artifact repositories used for dependency resolution to include maven central and nexus snapshots.
    // If you are operating in an environment where public repositories are not accessible, we recommend using a
    // virtual repository which mirrors both maven central and nexus snapshots.
    id("org.openrewrite.build.recipe-repositories") version "1.126.2"

    // Only needed when you want to apply the OpenRewriteBestPractices recipe to your recipes through
    // ./gradlew rewriteRun -Drewrite.activeRecipe=org.openrewrite.recipes.OpenRewriteBestPractices
    id("org.openrewrite.rewrite") version "7.1.2"
}
group = "io.micronaut.starter"
description = "Micronaut Starter OpenRewrite recipes."

dependencies {
    // The bom version can also be set to a specific version
    // https://github.com/openrewrite/rewrite-recipe-bom/releases
    implementation(platform("org.openrewrite.recipe:rewrite-recipe-bom:latest.release"))

    implementation("org.openrewrite:rewrite-java")
    implementation("org.openrewrite.recipe:rewrite-java-dependencies")
    implementation("org.openrewrite:rewrite-yaml")
    implementation("org.openrewrite.meta:rewrite-analysis")
    runtimeOnly("org.openrewrite:rewrite-java-17")
//
//    // Refaster style recipes need the rewrite-templating annotation processor and dependency for generated recipes
//    // https://github.com/openrewrite/rewrite-templating/releases
//    annotationProcessor("org.openrewrite:rewrite-templating:latest.release")
//    implementation("org.openrewrite:rewrite-templating")
//    // The `@BeforeTemplate` and `@AfterTemplate` annotations are needed for refaster style recipes
//    compileOnly("com.google.errorprone:error_prone_core:latest.release") {
//        exclude("com.google.auto.service", "auto-service-annotations")
//    }
//
//    // The RewriteTest class needed for testing recipes
//    testImplementation("org.openrewrite:rewrite-test")
//
//    // Need to have a slf4j binding to see any output enabled from the parser.
//    runtimeOnly("ch.qos.logback:logback-classic")
//
//    // Contains the OpenRewriteBestPractices recipe, which you can apply to your recipes
//    rewrite("org.openrewrite.recipe:rewrite-recommendations:latest.release")
}

rewrite {
    //configFile = file("src/main/resources/META-INF/rewrite/rewrite.yml")
    activeRecipe("micronaut.starter.feature.mockito.AddDependencyGradleMockito")
    setExportDatatables(true)
}
