#
#Tue Apr 01 15:46:05 UTC 2025
developers=James Kleeh
githubBranch=master
githubSlug=micronaut-projects/micronaut-starter
grailsVersion=3.3.8
groovyVersion=4.0.26
kafkaVersion=NA
micronautBuildVersion=1.1.5
micronautCoreVersion=4.8.10
micronautDocsVersion=2.0.0
micronautVersion=4.8.1-SNAPSHOT
org.gradle.caching=true
org.gradle.parallel=true
projectDesc=Generates Micronaut applications
projectGroup=io.micronaut.starter
projectUrl=https\://micronaut.io
projectVersion=4.8.1-SNAPSHOT
rockerVersion=2.1.0
spockVersion=2.3-groovy-4.0
title=Micronaut Starter
