#
#Thu Jul 31 14:13:22 UTC 2025
developers=James Kleeh
githubBranch=master
githubSlug=micronaut-projects/micronaut-starter
grailsVersion=3.3.8
groovyVersion=4.0.27
kafkaVersion=NA
micronautBuildVersion=1.1.5
micronautCoreVersion=4.9.10
micronautDocsVersion=2.0.0
micronautVersion=4.9.3
org.gradle.caching=true
org.gradle.parallel=true
projectDesc=Generates Micronaut applications
projectGroup=io.micronaut.starter
projectUrl=https\://micronaut-projects.github.io/micronaut-starter/latest/guide/
projectVersion=4.9.3
rockerVersion=2.2.1
spockVersion=2.3-groovy-4.0
title=Micronaut Starter
