#
#Wed Jun 03 18:37:07 UTC 2026
developers=Sergio del Amo
githubSlug=micronaut-projects/micronaut-starter
grailsVersion=3.3.8
groovyVersion=5.0.5
kafkaVersion=NA
micronautBuildVersion=1.1.5
micronautCoreVersion=5.0.3-SNAPSHOT
micronautDocsVersion=3.0.0
micronautVersion=5.0.3-SNAPSHOT
org.gradle.caching=true
org.gradle.parallel=true
projectDesc=Generates Micronaut applications
projectGroup=io.micronaut.starter
projectUrl=https\://micronaut.io
projectVersion=5.0.3-SNAPSHOT
rockerVersion=2.4.0
spockVersion=2.4-groovy-5.0
title=Micronaut Starter
