@import io.micronaut.starter.Project

@args (
Project project
)

FROM oracle/graalvm-ce:20.0.0-java8 as graalvm
# For JDK 11
#FROM oracle/graalvm-ce:20.0.0-java11 as graalvm
RUN gu install native-image

COPY . /home/app/@project.getAppName()
WORKDIR /home/app/@project.getAppName()

RUN native-image --no-server -cp build/libs/@project.getAppName()-*-all.jar

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/@project.getAppName()/@project.getAppName() /app/@project.getAppName()
ENTRYPOINT ["/app/@project.getAppName()"]
