package io.micronaut.starter.springboot.template;

import java.io.IOException;
import com.fizzed.rocker.ForIterator;
import com.fizzed.rocker.RenderingException;
import com.fizzed.rocker.RockerContent;
import com.fizzed.rocker.RockerOutput;
import com.fizzed.rocker.runtime.DefaultRockerTemplate;
import com.fizzed.rocker.runtime.PlainTextUnloadedClassLoader;
// import @ [1:1]
import io.micronaut.starter.application.Project;

/*
 * Auto generated code to render template io/micronaut/starter/springboot/template/springBootJavaApplicationTest.rocker.raw
 * Do not edit this file. Changes will eventually be overwritten by Rocker parser!
 */
@SuppressWarnings("unused")
public class springBootJavaApplicationTest extends com.fizzed.rocker.runtime.DefaultRockerModel {

    static public com.fizzed.rocker.ContentType getContentType() { return com.fizzed.rocker.ContentType.RAW; }
    static public String getTemplateName() { return "springBootJavaApplicationTest.rocker.raw"; }
    static public String getTemplatePackageName() { return "io.micronaut.starter.springboot.template"; }
    static public String getHeaderHash() { return "-1654727492"; }
    static public String[] getArgumentNames() { return new String[] { "project" }; }

    // argument @ [3:2]
    private Project project;

    public springBootJavaApplicationTest project(Project project) {
        this.project = project;
        return this;
    }

    public Project project() {
        return this.project;
    }

    static public springBootJavaApplicationTest template(Project project) {
        return new springBootJavaApplicationTest()
            .project(project);
    }

    @Override
    protected DefaultRockerTemplate buildTemplate() throws RenderingException {
        // optimized for performance (via rocker.optimize flag; no auto reloading)
        return new Template(this);
    }

    static public class Template extends com.fizzed.rocker.runtime.DefaultRockerTemplate {

        // package 
        static private final String PLAIN_TEXT_0_0 = "package ";
        // ;\n\nimport org.junit.jupiter.api.Test;\nimport org.springframework.boot.test.context.SpringBootTest;\n\n@SpringBootTest\nclass ApplicationTest {\n\n\t@Test\n\tvoid contextLoads() {\n\t}\n\n}
        static private final String PLAIN_TEXT_1_0 = ";\n\nimport org.junit.jupiter.api.Test;\nimport org.springframework.boot.test.context.SpringBootTest;\n\n@SpringBootTest\nclass ApplicationTest {\n\n\t@Test\n\tvoid contextLoads() {\n\t}\n\n}";

        // argument @ [3:2]
        protected final Project project;

        public Template(springBootJavaApplicationTest model) {
            super(model);
            __internal.setCharset("UTF-8");
            __internal.setContentType(getContentType());
            __internal.setTemplateName(getTemplateName());
            __internal.setTemplatePackageName(getTemplatePackageName());
            this.project = model.project();
        }

        @Override
        protected void __doRender() throws IOException, RenderingException {
            // PlainText @ [3:24]
            __internal.aboutToExecutePosInTemplate(3, 24);
            __internal.writeValue(PLAIN_TEXT_0_0);
            // ValueExpression @ [5:9]
            __internal.aboutToExecutePosInTemplate(5, 9);
            __internal.renderValue(project.getPackageName(), false);
            // PlainText @ [5:34]
            __internal.aboutToExecutePosInTemplate(5, 34);
            __internal.writeValue(PLAIN_TEXT_1_0);
        }
    }

}
