The subproject `starter-web-netty` provides an implementation that can be continuously deployed to Cloud Run as a GraalVM native image.

=== Running the Application Locally

Install GraalVM and the native image tool and then run:

[source,cmd]
----
$ docker build . -t micronaut-starter -f DockerfileCloudRun
$ docker run -p 8080:8080 micronaut-starter
----

And then visit http://localhost:8080/swagger/views/swagger-ui/index.html

=== Continuous Deployment

Micronaut Starter is continuously deployed to https://cloud.google.com/run[Google Cloud Run] as a native GraalVM application using GitHub Actions.

The https://github.com/micronaut-projects/micronaut-starter/actions?query=workflow%3A%22Snapshot+to+GCR%22[Snapshot to GCR Workflow] (defined by `.github/workflows/gcr-snapshot.yml`) deploys the application on each commit and the application can be accessed at the following URL:

https://micronaut-starter-staging-ucxwqnh6ka-uc.a.run.app/swagger/views/swagger-ui/index.html

=== Deploying the Application

To build and deploy the project yourself install set up the Google Cloud CLI then from the project root build the docker image and push it to Google Container Registry:

[source]
----
$ docker build . -t micronaut-starter -f DockerfileCloudRun
$ docker tag micronaut-starter gcr.io/[PROJECT ID]/micronaut-starter
$ docker push gcr.io/[PROJECT ID]/micronaut-starter
----

You are now ready to deploy your application:

[source]
----
$ gcloud beta run deploy --image gcr.io/[PROJECT ID]/micronaut-starter
----

Where `[PROJECT ID]` is replaced for your project ID.
You should see output like the following:

[source]
----
Service name: (micronaut-starter):
Deploying container to Cloud Run service [micronaut-starter] in project [PROJECT_ID] region [us-central1]

✓ Deploying... Done.
  ✓ Creating Revision...
  ✓ Routing traffic...
Done.
Service [micronaut-starter] revision [micronaut-starter-00004] has been deployed and is serving traffic at https://micronaut-starter-xxxxxxx-uc.a.run.app
----

The URL is the URL of your Cloud Run application.
