The subproject `starter-gcp-function` provides a function that can be deployed to Google Cloud Function.

=== Running the Function Locally

To run the function locally run:

[source,cmd]
----
./gradlew clean starter-gcp-function:runFunction
----

And then visit http://localhost:8081/application-types

=== Continuous Deployment

Micronaut Starter API is continuously deployed to https://cloud.google.com/functions[Google Cloud Function] as a Serverless Java application.

The https://github.com/micronaut-projects/micronaut-starter/actions?query=workflow%3A%22Snapshot+to+GCF%22[Snapshot to GCF Workflow] (defined by `.github/workflows/gcf-snapshot.yml`) deploys the application on each commit and the API can be accessed at the following URL:

https://us-central1-micronaut-projects.cloudfunctions.net/micronaut-starter-staging/application-types

=== Deploying the Function Yourself

To deploy the function first build the function with:

[source,bash]
----
$ ./gradlew clean starter-gcp-function:shadowJar
----

Then `cd` into the `starter-gcp-function/build/libs` directory (deployment has to be done from the location where the JAR lives):

[source,bash]
----
$ cd starter-gcp-function/build/libs
----

Now run:

[source,bash]
----
$ gcloud alpha functions deploy micronaut-starter --entry-point io.micronaut.gcp.function.http.HttpFunction --runtime java17 --trigger-http
----

Choose unauthenticated access if you don't need auth.

To obtain the trigger URL do the following:

[source,bash]
----
$ YOUR_HTTP_TRIGGER_URL=$(gcloud alpha functions describe micronaut-starter --format='value(httpsTrigger.url)')
----

You can then use this variable to test the function invocation:

[source,bash]
----
$ curl -i $YOUR_HTTP_TRIGGER_URL/create/app/example -o application.zip
----
