plugins {
    id "io.micronaut.build.internal.common"
    id "io.micronaut.application"
}

repositories {
    mavenCentral()
    maven {
        url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
        mavenContent {
            snapshotsOnly()
        }
    }
    maven {
        url = "https://central.sonatype.com/repository/maven-snapshots/"
        mavenContent {
            snapshotsOnly()
        }
    }
}

dependencies {
    implementation(project(":starter-api"))
    implementation(project(":micronaut-cli"))
    implementation(project(":starter-web-netty"))
    implementation("ch.qos.logback:logback-classic")
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testImplementation("org.junit.jupiter:junit-jupiter-params")
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

configurations.all {
    resolutionStrategy {
        force "io.micronaut:micronaut-core-bom:$micronautCoreVersion"
        force "io.micronaut:micronaut-inject-groovy:$micronautCoreVersion"
    }
}

graalvmNative {
    binaries {
        all {
            buildArgs.add("--report-unsupported-elements-at-runtime")
        }
    }
}
java {
    sourceCompatibility = JavaVersion.toVersion("21")
    targetCompatibility = JavaVersion.toVersion("21")
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}