@import io.micronaut.starter.application.Project

@args (
Project project,
String jarFile
)

FROM oracle/graalvm-ce:20.1.0-java8 as graalvm
# For JDK 11
#FROM oracle/graalvm-ce:20.1.0-java11 as graalvm
RUN gu install native-image

COPY . /home/app/@project.getName()
WORKDIR /home/app/@project.getName()

RUN native-image --no-server -cp @jarFile

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/@project.getName()/@project.getName() /app/@project.getName()
ENTRYPOINT ["/app/@project.getName()"]
