@import io.micronaut.starter.Project
@import io.micronaut.starter.options.BuildTool

@args (
Project project,
BuildTool buildTool
)

FROM oracle/graalvm-ce:20.0.0-java8 as graalvm
# For JDK 11
#FROM oracle/graalvm-ce:20.0.0-java11 as graalvm
RUN gu install native-image

COPY . /home/app/@project.getName()
WORKDIR /home/app/@project.getName()

@if (buildTool.equals(BuildTool.GRADLE)) {
RUN native-image --no-server -cp build/libs/@project.getName()-*-all.jar
} else {
RUN native-image --no-server -cp target/@project.getName()-*.jar
}

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/@project.getName()/@project.getName() /app/@project.getName()
ENTRYPOINT ["/app/@project.getName()"]
