@import io.micronaut.starter.application.Project
@import io.micronaut.starter.options.JdkVersion

@args (
Project project,
String jarFile,
JdkVersion jdkVersion
)

@if (jdkVersion == JdkVersion.JDK_8) {
FROM oracle/graalvm-ce:20.2.0-java8 as graalvm
} else if (jdkVersion.majorVersion() <= JdkVersion.JDK_11.majorVersion()) {
FROM oracle/graalvm-ce:20.2.0-java11 as graalvm
}
RUN gu install native-image

COPY . /home/app/@project.getName()
WORKDIR /home/app/@project.getName()

RUN native-image -cp @jarFile

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/@project.getName()/@project.getName() /app/@project.getName()
ENTRYPOINT ["/app/@project.getName()"]
