@import io.micronaut.starter.application.Project

@args (
Project project,
String jarFile
)

FROM openjdk:14-alpine
COPY @jarFile @(project.getName()).jar
EXPOSE 8080
CMD ["java", "-Dcom.sun.management.jmxremote", "-Xmx128m", "-jar", "@(project.getName()).jar"]