Args = --initialize-at-build-time=io.micronaut.starter.cli.rocker \
      --initialize-at-run-time=io.netty.handler.pcap.PcapWriteHandler,io.netty.handler.pcap.PcapWriteHandler$WildcardAddressHolder \
      --initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils