plugins {
    id "io.micronaut.internal.starter.test-module"
}

repositories {
    mavenCentral()
    maven { url = uri("https://repo.gradle.org/gradle/libs-releases") }
}

dependencies {
    testImplementation(project(":test-utils"))
    testImplementation(project(":starter-core"))
    testImplementation(project(":micronaut-cli"))
    testImplementation("ch.qos.logback:logback-classic")
}
