name: Maven Central Sync
on:
  release:
    types: [published]
jobs:
  build:
    name: Maven Central Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          ref: ${{ github.head_ref }}
      - name: Set the current release version
        id: release_version
        run: |
          release_version=${GITHUB_REF:11}
          sed -i "s/^projectVersion.*$/projectVersion\=${release_version}/" gradle.properties
          echo ::set-output name=release_version::${release_version}
      - name: Publish to Maven Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_FILE: ${{ secrets.GPG_FILE }}
        run: echo $GPG_FILE | base64 -d > secring.gpg && ./gradlew publish closeAndReleaseRepository