name: Linux Native CLI
on:
  push:
    branches:
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    name: Builds Linux Native CLI
    runs-on: ubuntu-latest
    steps:
      - name: "⬇ Checkout the repository"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: "☕️ Setup GraalVM CE"
        uses: graalvm/setup-graalvm@v1.4.5
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          native-image-musl: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "📸 Build the Native Image (with libc=musl)"
        run: ./gradlew micronaut-cli:nativeCompile --no-daemon -Pmusl
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          DEVELOCITY_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME  }}
          DEVELOCITY_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
      - name: "✅ Verify Build"
        run: ./starter-cli/build/native/nativeCompile/mn --version
      - name: "✅ Verify Create App"
        run: ./starter-cli/build/native/nativeCompile/mn create-app test
      - name: "👷‍♀️Package Build"
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          mkdir -p mn-linux-amd64-snapshot/bin
          mv ./starter-cli/build/native/nativeCompile/mn mn-linux-amd64-snapshot/bin
          cp ./LICENSE mn-linux-amd64-snapshot/
          zip -r mn-linux-amd64-snapshot.zip ./mn-linux-amd64-snapshot
      - name: "🆙 Upload Snapshot"
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/4.10.x'
        uses: actions/upload-artifact@v7
        with:
          name: mn-linux-amd64-snapshot
          path: mn-linux-amd64-snapshot.zip
