name: Windows Native CLI
on:
  push:
    branches:
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[1-9]+.[0-9]+.x'
jobs:
  build:
    name: Builds Windows Native CLI
    runs-on: windows-latest
    steps:
      - name: "⬇ Checkout the repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: "☕️ Setup GraalVM"
        uses: graalvm/setup-graalvm@v1.5.3
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "📸 Build the Native Image"
        run: ./gradlew micronaut-cli:nativeCompile --no-daemon
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          DEVELOCITY_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME  }}
          DEVELOCITY_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
      - name: "✅ Verify Build (Powershell)"
        shell: powershell
        run: ./starter-cli/build/native/nativeCompile/mn.exe --version
      - name: "✅ Verify Create App (Powershell)"
        run: ./starter-cli/build/native/nativeCompile/mn.exe create-app test
      - name: "✅ Verify Build (CMD)"
        shell: cmd
        run: starter-cli\\build\\native\\nativeCompile\\mn --version
      - name: "✅ Verify Create App (CMD)"
        shell: cmd
        run: starter-cli\\build\\native\\nativeCompile\\mn create-app test2
      - name: "🤐 ZIP Archive"
        run: |
          New-Item "./mn-win-amd64-snapshot/bin" -ItemType Directory -ea 0
          Move-Item -Path ./starter-cli/build/native/nativeCompile/mn.exe -Destination "./mn-win-amd64-snapshot/bin"
          Copy-Item "./LICENSE" -Destination "./mn-win-amd64-snapshot"
          Compress-Archive -Path "./mn-win-amd64-snapshot" -Update -DestinationPath ./mn-win-amd64-snapshot.zip
      - name: "🆙 Upload Snapshot"
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/5.0.x'
        uses: actions/upload-artifact@v7
        with:
          name: mn-win-amd64-snapshot
          path: ./mn-win-amd64-snapshot.zip
